name: Upload Report to DefectDojo
description: "Realiza el checkout, configura Python y ejecuta el script uploadtodojo.py"
inputs:
  scan_type:
    description: "Tipo de scan"
    required: true
  file_path:
    description: "Ruta del archivo a subir"
    required: true
  engagement_id:
    description: "ID del engagement"
    required: true
  product_id:
    description: "ID del producto (opcional)"
    required: false
runs:
  using: composite
  steps:
    - name: Checkout repositorio org
      uses: actions/checkout@v3
      with:
        repository: skacode/org
        ref: main
        path: org

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Ejecutar upload script
      env:
        DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
      run: |
        python org/.github/scripts/uploadtodojo.py \
          --scan_type "${{ inputs.scan_type }}" \
          --file_path "${{ inputs.file_path }}" \
          --engagement_id "${{ inputs.engagement_id }}" \
          --product_id "${{ inputs.product_id }}"

